spring:
  application:
    name: api-services
  kafka:
    bootstrap-servers: localhost:9094,localhost:9194,localhost:9294
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: PLAIN
      sasl.jaas.config: >
        org.apache.kafka.common.security.plain.PlainLoginModule required
        username="user" password="user-secret";
      ssl.truststore.location: main-kafka-cluster/sasl-ssl-properties/kafka-creds/kafka-1/certs/kafka-1.truststore.jks
      ssl.truststore.password: your-password
      ssl.keystore.location: main-kafka-cluster/sasl-ssl-properties/kafka-creds/kafka-1/certs/kafka-1.keystore.jks
      ssl.keystore.password: your-password
      ssl.key.password: your-password
      ssl.endpoint.identification.algorithm: ""

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: spring-security-consumer
      auto-offset-reset: earliest

  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: mypassword
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true


product:
  initialization:
    enabled: true
    file: "data/products.json"