FROM confluentinc/cp-kafka-connect:7.7.1

# копируем JAR из контекста (./kafka-connect) в /opt/
#COPY jmx_prometheus_javaagent-0.15.0.jar /opt/jmx_prometheus_javaagent-0.15.0.jar
#COPY kafka-connect.yml /opt/kafka-connect.yml

